executable = /bin/bash
arguments = src/baselines/run_baseline_limit.sh $(eval) $(model) $(Cluster) $(limit)
environment = "HOME=$ENV(HOME)"
error = logs/test_$(Cluster).err
output = logs/test_$(Cluster).out
log = logs/test_$(Cluster).log
request_memory = 32768
request_cpus = 16
request_gpus = 1
requirements = TARGET.CUDADeviceName == "NVIDIA H100 80GB HBM3" && Machine != "i104.internal.cluster.is.localnet"
request_disk=200G
+BypassLXCfs="true"
queue